### ISSUE TITLE
user should write in private chat

### ISSUE THREAD

**Issue by Pinzia** [WEEE-Open/politoteams-telegram-bot#4]
- user enters group chat
- bot sends message to enter private chat
- user go to private chat
- user /start
- user select the team
Bot has to remember the group chat id to change the custom_title

**Comment by lvps** [comment]
Two random suggestions:
* An environment variable for the group chat ID (it's static and there's only one group anyway)
* Make it possible for other team members (of the same team) to set the team for their teammates, and for administrators (?) to set the team for everyone

For the second point, what I'm thinking about is e.g. someone joins the group and sends a message like "Hey everyone, I'm from team Foo!" and another team member can reply to the message with `/setteam` or something similar, or an administrator can reply with `/setteam Foo`
